### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by cal97g** [kroitor/asciichart#12]
Python output looks terrible in a terminal, and there isn't any documentation on python support.

Also, I keep getting 0 division errors trying to plot floats.

Help?

**Comment by kroitor** [comment]
Can you post some code and output to reproduce it?

**Comment by MrZeusTheCoder** [comment]
@cal97g, I believe the issue you are having is an issue of the graph being larger than your terminal's. You can fix it by either making your terminal larger. The graph might be larger than you can make your terminal. In that case reduce the number of data-points you have.

**Comment by cal97g** [comment]
@kroitor @MrZeusTheCoder - possibly this is the case. Is it possible for the script to sample the data points if this is the case? It should be aware of terminal sizing right?

My graph was 1000's of data points. Don't currently have it but may be able to reproduce.

**Comment by kroitor** [comment]
> Is it possible for the script to sample the data points if this is the case? It should be aware of terminal sizing right?

It is, but adding the functionality to track the size of the terminal window will bloat this repo and it is something that we would like to leave outside of the package – for compatibility reasons (determining width on Windows and *nix is done differently, so to support for auto-width, we will have to add an amount of code comparable to a micro OS, whereas this entire package is less than 100 lines... This isn't what we want, as we'd like to keep it compact, so that you could run it on your watch or with your Arduino...

> My graph was 1000's of data points. Don't currently have it but may be able to reproduce.

Yep, as documented on the main page: *The width of the chart will always equal the length of data series. The height and range are determined automatically.* So, if you want to have a reduced set of data points, reduce them according to your needs before passing the filtered set to the plotting function.

There are standalone packages that allow to adjust for screen width in text mode, check out [curses](https://www.google.ru/search?newwindow=1&biw=1440&bih=798&tbm=isch&sa=1&ei=2hnkW8zaI8_NrgSY0Y3IDg&q=curses+python&oq=curses+python&gs_l=img.3..0j0i30k1j0i8i30k1l2j0i24k1l6.33328.33328.0.33525.1.1.0.0.0.0.80.80.1.1.0....0...1c.1.64.img..0.1.79....0.JhRgMUjtNM4), [ncurses](https://www.google.com/search?q=ncurses+python&newwindow=1&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiOtZbV1MTeAhWjlYsKHX3mD3cQ_AUIDigB&biw=1440&bih=798) or [blessed](https://github.com/chjj/blessed), for example.

Hope this answers your question, let us know if not. Closing it for now, if you don't mind, feel free to reopen it if needed or just ask further questions if you have more, will be happy to reply asap.
